### ISSUE TITLE
Support for Amplify CLI 1.1.0

### ISSUE THREAD

**Issue by wizage** [wizage/amplify-elemental-plugin#13]
Currently the plugin doesn't support the new CLI. This is a major bug.

```
Provide a friendly name for your resource to be used as a label for this categ
ory in the project: (multi-env) 
>> Resource name should be alphanumeric
```

Prevents from starting the project. Using this issue to track all bugs around 1.1.0

**Comment by wizage** [comment]
Strike this issue above as it was a project name failure.

**Comment by wizage** [comment]
First real error:
```
/Users/sampatze/Documents/Projects/amplify-cli/packages/amplify-cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type undefined
    at Module.require (internal/modules/cjs/loader.js:631:11)
    at require (internal/modules/cjs/helpers.js:22:18)
    at copyFilesToS3 (/Users/sampatze/Documents/Projects/amplify-elemental-plugin/extensions/livestream-push.js:98:20)
    at addLivestream (/Users/sampatze/Documents/Projects/amplify-elemental-plugin/extensions/livestream-push.js:90:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by wizage** [comment]
Fixed.
New Error:
`Parameters: [env] do not exist in the template`
This is in CloudFormation
